name: Enforce Branching Rules

on:
  pull_request:
    branches:
      - 'ui/orion/release/*'  # Only run on PRs targeting release branches

jobs:
  check_pr_description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Check if PR description is provided and is at least 100 characters
        run: |
          PR_BODY=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r '.body')
          PR_LENGTH=${#PR_BODY}
          if [[ -z "$PR_BODY" || "$PR_BODY" == "null" || $PR_LENGTH -lt 100 ]]; then
            echo "Error: PR description is required and must be at least 100 characters."
            exit 1
          fi

  check_branch_name:
    runs-on: ubuntu-latest
    needs: check_pr_description
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Check if source branch starts with ui/orion/feature/
        run: |
          SOURCE_BRANCH=${{ github.head_ref }}
          if [[ ! "$SOURCE_BRANCH" =~ ^ui/orion/feature/ ]]; then
            echo "Error: Source branch must start with 'ui/orion/feature/'"
            exit 1
          fi

  merge_checks:
    runs-on: ubuntu-latest
    needs: check_branch_name
    steps:
      - name: Merge PR
        run: |
          echo "All checks passed. PR is ready to be merged!"
